# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMDBApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit'
pod 'SwiftLint'
pod 'Kingfisher', '7.6.1'
pod 'Alamofire'

end
